version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq